export const scheduleStatuses = ["Active", "Pending"];
export const educationTypeOptions = [
  "School",
  "Academy/Coaching",
  "Colleges",
  "Universities",
];

const weekdays = [1, 2, 3, 4, 5];
const makeTemplate = (type, slots) =>
  slots.map(
    (
      {
        subject,
        section,
        instructor,
        startTime,
        endTime,
        room,
        isBreak = false,
      },
      index,
    ) => ({
      id: `template-${type.toLowerCase().replace(/[^a-z]+/g, "-")}-${index}`,
      subject,
      section: isBreak ? "All sections" : section,
      program: type,
      instructor: isBreak ? "Campus schedule" : instructor,
      room,
      days: weekdays,
      startTime,
      endTime,
      status: "Active",
      isBreak,
    }),
  );

export const timetableTemplates = {
  School: makeTemplate("School", [
    {
      subject: "Assembly & Homeroom",
      section: "Grade 8-A",
      instructor: "Ms. Ayesha Khan",
      startTime: "08:00",
      endTime: "08:30",
      room: "School grounds",
    },
    {
      subject: "English Language",
      section: "Grade 8-A",
      instructor: "Ms. Sana Ahmed",
      startTime: "08:30",
      endTime: "09:20",
      room: "Room 201",
    },
    {
      subject: "Mathematics",
      section: "Grade 8-A",
      instructor: "Mr. Bilal Raza",
      startTime: "09:20",
      endTime: "10:10",
      room: "Room 201",
    },
    {
      subject: "Morning Break",
      startTime: "10:10",
      endTime: "10:40",
      room: "Break area",
      isBreak: true,
    },
    {
      subject: "General Science",
      section: "Grade 8-A",
      instructor: "Dr. Hina Iqbal",
      startTime: "10:40",
      endTime: "11:30",
      room: "Science Lab",
    },
    {
      subject: "Pakistan Studies",
      section: "Grade 8-A",
      instructor: "Mr. Hamza Ali",
      startTime: "11:30",
      endTime: "12:20",
      room: "Room 201",
    },
    {
      subject: "Lunch & Prayer Break",
      startTime: "12:20",
      endTime: "12:55",
      room: "Break area",
      isBreak: true,
    },
    {
      subject: "Computer Studies",
      section: "Grade 8-A",
      instructor: "Mr. Usman Tariq",
      startTime: "12:55",
      endTime: "13:45",
      room: "IT Lab",
    },
  ]),
  "Academy/Coaching": makeTemplate("Academy/Coaching", [
    {
      subject: "Mathematics (MDCAT)",
      section: "MDCAT Evening",
      instructor: "Dr. Farhan Malik",
      startTime: "16:00",
      endTime: "17:15",
      room: "Hall A",
    },
    {
      subject: "Short Break",
      startTime: "17:15",
      endTime: "17:45",
      room: "Common area",
      isBreak: true,
    },
    {
      subject: "Physics (MDCAT)",
      section: "MDCAT Evening",
      instructor: "Mr. Saad Ahmed",
      startTime: "17:45",
      endTime: "19:00",
      room: "Hall A",
    },
    {
      subject: "Chemistry (MDCAT)",
      section: "MDCAT Evening",
      instructor: "Ms. Maham Khan",
      startTime: "19:00",
      endTime: "20:15",
      room: "Lab 2",
    },
  ]),
  Colleges: makeTemplate("Colleges", [
    {
      subject: "English Literature",
      section: "FA Part II",
      instructor: "Ms. Nadia Shah",
      startTime: "08:30",
      endTime: "09:45",
      room: "Room 12",
    },
    {
      subject: "Statistics",
      section: "ICS Part II",
      instructor: "Mr. Waqas Ahmed",
      startTime: "09:45",
      endTime: "11:00",
      room: "Room 21",
    },
    {
      subject: "College Break",
      startTime: "11:00",
      endTime: "11:40",
      room: "Student area",
      isBreak: true,
    },
    {
      subject: "Computer Science",
      section: "ICS Part II",
      instructor: "Mr. Junaid Hussain",
      startTime: "11:40",
      endTime: "12:55",
      room: "Computer Lab",
    },
    {
      subject: "Physics Practical",
      section: "ICS Part II",
      instructor: "Dr. Maryam Iqbal",
      startTime: "12:55",
      endTime: "14:10",
      room: "Physics Lab",
    },
  ]),
  Universities: makeTemplate("Universities", [
    {
      subject: "Software Engineering",
      section: "BSCS-5A",
      instructor: "Dr. Usman Khan",
      startTime: "09:00",
      endTime: "10:15",
      room: "Lab 302",
    },
    {
      subject: "Database Systems",
      section: "BSCS-5A",
      instructor: "Dr. Sara Nadeem",
      startTime: "10:15",
      endTime: "11:30",
      room: "Lab 302",
    },
    {
      subject: "Tea Break",
      startTime: "11:30",
      endTime: "12:00",
      room: "Student area",
      isBreak: true,
    },
    {
      subject: "Operating Systems",
      section: "BSCS-5A",
      instructor: "Mr. Ahmed Raza",
      startTime: "12:00",
      endTime: "13:15",
      room: "Lecture Hall B",
    },
    {
      subject: "Prayer & Lunch Break",
      startTime: "13:15",
      endTime: "14:15",
      room: "Student area",
      isBreak: true,
    },
    {
      subject: "Artificial Intelligence",
      section: "BSCS-5A",
      instructor: "Dr. Hiba Farooq",
      startTime: "14:15",
      endTime: "15:30",
      room: "AI Research Lab",
    },
  ]),
};

export const initialSchedules = [
  {
    id: "schedule-1",
    subject: "Advanced Web Design",
    section: "CS-4A",
    program: "BS Computer Science",
    instructor: "Dr. Usman Khan",
    room: "Lab 302",
    days: [1, 3],
    startTime: "10:00",
    endTime: "12:00",
    status: "Active",
  },
  {
    id: "schedule-2",
    subject: "Data Structures & Algorithms",
    section: "CS-3B",
    program: "BS Computer Science",
    instructor: "Dr. Usman Khan",
    room: "Hall B",
    days: [2, 4],
    startTime: "14:00",
    endTime: "15:30",
    status: "Pending",
  },
  {
    id: "schedule-3",
    subject: "Artificial Intelligence",
    section: "CS-4B",
    program: "BS Computer Science",
    instructor: "Dr. Usman Khan",
    room: "AI Research Lab",
    days: [5],
    startTime: "09:00",
    endTime: "12:00",
    status: "Active",
  },
];
