// Frontend demonstration records transcribed from the approved reference image.
export const campusStudents = [
  {
    id: 'std-1',
    name: 'Ali Raza',
    initials: 'AR',
    roll: 'NUST-CS-2023-042',
    email: 'ali.raza@nust.edu.pk',
    program: 'BS Computer Science',
    specialization: 'Artificial Intelligence & Software',
    section: 'CS-4A',
    semester: '4th Semester',
    batch: 'Spring 2025',
    campus: 'NUST Main Campus (H-12)',
    status: 'Active',
    guardian: 'Muhammad Raza',
    phone: '+92 333 5551234',
    guardianPhone: '+92 300 9998877',
    tone: 'green',
    attendance: '94.2%',
    cgpa: '3.85',
    subjects: 'Advanced Web Design, Data Structures, AI',
  },
  {
    id: 'std-2',
    name: 'Zainab Bilal',
    initials: 'ZB',
    roll: 'NUST-CS-2023-088',
    email: 'zainab.b@nust.edu.pk',
    program: 'BS Computer Science',
    specialization: 'Information Security & Networks',
    section: 'CS-4B',
    semester: '4th Semester',
    batch: 'Spring 2025',
    campus: 'NUST Main Campus (H-12)',
    status: 'Pending',
    guardian: 'Bilal Ahmed',
    phone: '+92 331 4455667',
    guardianPhone: '+92 301 4443322',
    tone: 'blue',
    attendance: '88.5%',
    cgpa: '3.62',
    subjects: 'Machine Learning, Neural Networks, Cryptography',
  },
  {
    id: 'std-3',
    name: 'Usman Safdar',
    initials: 'US',
    roll: 'NUST-CS-2023-101',
    email: 'usman.s@nust.edu.pk',
    program: 'BS Software Engineering',
    specialization: 'Cloud Computing & DevOps',
    section: 'SE-3A',
    semester: '3rd Semester',
    batch: 'Spring 2025',
    campus: 'NUST Main Campus (H-12)',
    status: 'Active',
    guardian: 'Safdar Ali',
    phone: '+92 345 8899001',
    guardianPhone: '+92 333 5557733',
    tone: 'purple',
    attendance: '96.0%',
    cgpa: '3.91',
    subjects: 'Software Architecture, Agile QA, Database Systems',
  },
  {
    id: 'std-4',
    name: 'Maryam Ahmed',
    initials: 'MA',
    roll: 'NUST-CS-2023-115',
    email: 'maryam.a@nust.edu.pk',
    program: 'BS Computer Science',
    specialization: 'Data Science & Analytics',
    section: 'CS-2B',
    semester: '2nd Semester',
    batch: 'Spring 2025',
    campus: 'NUST Main Campus (H-12)',
    status: 'Active',
    guardian: 'Ahmed Khan',
    phone: '+92 322 1122334',
    guardianPhone: '+92 321 8887766',
    tone: 'amber',
    attendance: '92.4%',
    cgpa: '3.74',
    subjects: 'Operating Systems, Database Systems, Linear Algebra',
  },
  {
    id: 'std-5',
    name: 'Hamza Tariq',
    initials: 'HT',
    roll: 'NUST-EE-2023-019',
    email: 'hamza.t@nust.edu.pk',
    program: 'BS Electrical Engineering',
    specialization: 'Digital Signal Processing & IoT',
    section: 'EE-4A',
    semester: '4th Semester',
    batch: 'Spring 2025',
    campus: 'NUST Main Campus (H-12)',
    status: 'Active',
    guardian: 'Tariq Mehmood',
    phone: '+92 334 2233445',
    guardianPhone: '+92 300 4455667',
    tone: 'cyan',
    attendance: '91.0%',
    cgpa: '3.58',
    subjects: 'Digital Signal Processing, IoT Systems, Microcontrollers',
  },
  {
    id: 'std-6',
    name: 'Fatima Noor',
    initials: 'FN',
    roll: 'NUST-SE-2023-054',
    email: 'fatima.n@nust.edu.pk',
    program: 'BS Software Engineering',
    specialization: 'Full Stack & Mobile Development',
    section: 'SE-3B',
    semester: '3rd Semester',
    batch: 'Spring 2025',
    campus: 'NUST Main Campus (H-12)',
    status: 'Active',
    guardian: 'Noor Hassan',
    phone: '+92 313 7788990',
    guardianPhone: '+92 312 6677889',
    tone: 'rose',
    attendance: '95.5%',
    cgpa: '3.88',
    subjects: 'Software Testing, Cloud Native Apps, Mobile UI',
  },
  {
    id: 'std-7',
    name: 'Bilal Shah',
    initials: 'BS',
    roll: 'NUST-CS-2023-140',
    email: 'bilal.shah@nust.edu.pk',
    program: 'BS Computer Science',
    specialization: 'Cybersecurity & Cryptography',
    section: 'CS-1A',
    semester: '1st Semester',
    batch: 'Spring 2025',
    campus: 'NUST Main Campus (H-12)',
    status: 'Active',
    guardian: 'Shah Nawaz',
    phone: '+92 305 6677881',
    guardianPhone: '+92 345 9988776',
    tone: 'emerald',
    attendance: '89.0%',
    cgpa: '3.42',
    subjects: 'Programming Fundamentals, Discrete Mathematics, ICT',
  },
  {
    id: 'std-8',
    name: 'Ayesha Siddiqui',
    initials: 'AS',
    roll: 'NUST-SE-2023-076',
    email: 'ayesha.s@nust.edu.pk',
    program: 'BS Software Engineering',
    specialization: 'Human-Computer Interaction',
    section: 'SE-2A',
    semester: '2nd Semester',
    batch: 'Spring 2025',
    campus: 'NUST Main Campus (H-12)',
    status: 'Active',
    guardian: 'Asim Siddiqui',
    phone: '+92 301 9988772',
    guardianPhone: '+92 302 3344556',
    tone: 'indigo',
    attendance: '97.2%',
    cgpa: '3.96',
    subjects: 'Object Oriented Programming, UI/UX Design, Data Structures',
  },
];

export const campusClasses = [
  { subject: 'Advanced Web Design', section: 'CS-4A', days: 'Mon, Wed', time: '10:00 AM – 11:30 AM', room: 'Lab 302' },
  { subject: 'Data Structures & Algorithms', section: 'CS-3B', days: 'Tue, Thu', time: '02:00 PM – 03:30 PM', room: 'Hall B' },
  { subject: 'Artificial Intelligence', section: 'CS-4B', days: 'Fri', time: '11:00 AM – 01:00 PM', room: 'AI Research Lab' },
];

export function filterCampusStudents(students, { query, program, status }) {
  const search = query.trim().toLowerCase();
  return students.filter((student) =>
    (!program || student.program === program) &&
    (!status || student.status === status) &&
    (!search || `${student.name} ${student.roll}`.toLowerCase().includes(search)),
  );
}
